// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4uFla_K4KLN5ZFGUWNOOHqEg7OEG5Ytw',
    appId: '1:639401568459:web:ab58155d52216249e4934e',
    messagingSenderId: '639401568459',
    projectId: 'fairsplit-oquy36',
    authDomain: 'fairsplit-oquy36.firebaseapp.com',
    storageBucket: 'fairsplit-oquy36.firebasestorage.app',
    measurementId: 'G-TTZ2P0S366',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIW5-ap3iGsnurWoJaq9nlbxCUTwtsmtA',
    appId: '1:639401568459:android:873fc8aa17c5697ee4934e',
    messagingSenderId: '639401568459',
    projectId: 'fairsplit-oquy36',
    storageBucket: 'fairsplit-oquy36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNr6p_SeUYQ6yK-U4nl30PJgissKY11Q',
    appId: '1:639401568459:ios:28fb7e8023d032d5e4934e',
    messagingSenderId: '639401568459',
    projectId: 'fairsplit-oquy36',
    storageBucket: 'fairsplit-oquy36.firebasestorage.app',
    iosBundleId: 'com.example.fairsplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNr6p_SeUYQ6yK-U4nl30PJgissKY11Q',
    appId: '1:639401568459:ios:28fb7e8023d032d5e4934e',
    messagingSenderId: '639401568459',
    projectId: 'fairsplit-oquy36',
    storageBucket: 'fairsplit-oquy36.firebasestorage.app',
    iosBundleId: 'com.example.fairsplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4uFla_K4KLN5ZFGUWNOOHqEg7OEG5Ytw',
    appId: '1:639401568459:web:fa12725c0c4b0788e4934e',
    messagingSenderId: '639401568459',
    projectId: 'fairsplit-oquy36',
    authDomain: 'fairsplit-oquy36.firebaseapp.com',
    storageBucket: 'fairsplit-oquy36.firebasestorage.app',
    measurementId: 'G-25BC87JZCX',
  );
}
